### ISSUE TITLE
Wrong format for the parameter "scope" in Azure DevOps pipelines

### ISSUE THREAD

**Issue by arnaudluti** [GreyCorbel/azure-automation-devops-integration#11]
Hello,

The "scope" parameter of the task ManageAutomationAccount@1 in an Azure DevOps pipeline seems to expect a string,
![image](https://github.com/user-attachments/assets/c10ab84e-0419-4586-afc4-0c924de45b49)

I've tried this syntax : 
![image](https://github.com/user-attachments/assets/dfe0633f-1472-4241-85a1-1aa91663d1f5)

This obviously doesn't work during a deployment, the pipeline executes with an empty "scope" and does nothing:
![image](https://github.com/user-attachments/assets/213eac85-3136-4282-a64f-e508be7053f0)

If i set an unique value like "Schedules"...
![image](https://github.com/user-attachments/assets/8bc17bd4-0ae5-40d5-9a2b-cca84ac8e36c)

...Pipeline works and creates the schedule.   
![image](https://github.com/user-attachments/assets/a57322ff-6586-41b9-8563-07f72124c174)

I've tried to execute the module on my computer directly with PowerShell and i confirm that the setting "scope" is expecting an array and not a string.  
![image](https://github.com/user-attachments/assets/a6e0b183-3744-4595-9e15-7b553dd5b3c0)

**Comment by arnaudluti** [comment]
update : format should be set as a string with comma separator in azdo, like that it seems to be working,
![image](https://github.com/user-attachments/assets/2191f913-6086-4fb6-a89a-a3e786e9b9c7)

**Comment by jformacek** [comment]
Hello,
You're right - tasks SDK does not support parameter of type string[] - this is why we pass array as single string and convert it back to array inside the code - see [source code of ManageAutomationAccount task](https://github.com/GreyCorbel/azure-automation-devops-integration/blob/4fbe312d1f7ee06ee4a0460701f2e1cc4e4c8d21/Tasks/Manage-AutomationAccount/Manage-AutomationAccount.ps1#L4) for implementation and allowed delimiters.

Does it answer your question?

**Comment by arnaudluti** [comment]
Yes, and thanks for the work!
