### ISSUE TITLE
Runbook deployment for powershell 7.2 fails with 404 error

### ISSUE THREAD

**Issue by RussOBrienSea** [GreyCorbel/azure-automation-devops-integration#3]
As stated above, runbooks targeting powershell 7.2 now fail to deploy with error:

##[error]The remote server returned an error: (404) Not Found.
##[error]PowerShell exited with code '1'.

I think this may be due to the API version 2022-06-30-preview no longer being valid, though I'm struggling to find that documented.

**Comment by jformacek** [comment]
Seems like MS changed API's a bit as a part of Ignite wave of news. 

We updated accordingly, please retest.

Thanks for reporting

**Comment by RussOBrienSea** [comment]
This fix works, many thanks for the quick response!
